### ISSUE TITLE
some bugs found

### ISSUE THREAD

**Issue by erichuang2015** [LearnCodeWeb/PHP-pagination-class-with-Bootstrap-4#1]
Hi

great job for the class. but I can see a bug here in the demo

When I go to the demo https://demo.learncodeweb.com/php/php-pagination-class-with-bootstrap-4/index.php?tb1=Africa , it works fine

and then I change the page items limit to 'All'  to show all the items in one page, the html structure will break into ugly look

**Comment by mianzaid** [comment]
Thank you for showing your interest.
Pagination with bootstrap 4 is updated on the [demo](https://demo.learncodeweb.com/php/php-pagination-class-with-bootstrap-4/index.php?tb1=Africa) and on [bitbucket ](https://bitbucket.org/snippets/zaidbinkhalid/nejbyy)
